### ISSUE TITLE
Still have problem with modifiers....

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#11]
1) Start current contract (debug all)
2) Run scenario1 which sets everything up

The last instruction is buyGoldInCurrency(MYR,25600) and step to the following line

![image](https://cloud.githubusercontent.com/assets/1858302/22804703/3be3a57c-ef55-11e6-97fe-eec282903202.png)

```
NewDecimal memory goldValue = divideNewDecimal(cashValue, getGoldSellPriceInND(userBalance.currency,msg.sender));
```

From debugger you can see values of currency...

trace in

![image](https://cloud.githubusercontent.com/assets/1858302/22804733/5ed1fd90-ef55-11e6-9dea-433effbc23ab.png)

But the data is shown as 

![image](https://cloud.githubusercontent.com/assets/1858302/22804758/7907cf1e-ef55-11e6-82d8-7ebbbf02da8d.png)

(should be tier = 0, currency = MYR)

After which we are out of gas and the sandbox stops

![image](https://cloud.githubusercontent.com/assets/1858302/22804808/b5740832-ef55-11e6-861e-1b0cc149fe1e.png)

**Comment by DaveAppleton** [comment]
After this, Ethereum Studio went into a Looooong reboot.
Had to restart ....

**Comment by asinyagin** [comment]
Fixed
