### ISSUE TITLE
Edit window stops receiving key entries 

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#12]
MacBook - OSX 10.11.6

Chrome : Version 56.0.2924.87 (64-bit)

After a while of using the IDE I have reached a point where I cannot insert any text into the IDE, Bash windows etc. 

Arrows, CMD-Save etc awork fine. 
So I can type elsewhere and paste (cmd-V).

This is probably something stupid that I did - but it should not take this long to figure it out.

**Comment by romanman** [comment]
can you recreate it? is it happens constantly?

**Comment by DaveAppleton** [comment]
This seems to have been an issue with Chrome on my machine. 
I eventually rebooted and it seemed to have been solved.
