### ISSUE TITLE
Structure strings not displayed or displayed incorrectly

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#13]
In following contract snippet, debug & set BP at "*"

debug and call with `MYR` / `0xdedb49385ad5b94a16f236a6890cf9e0b1e30392`

```
    struct tierBase {
        address                         banker;
        bool                            initialised;
        mapping(uint16 => tierEntry)    tierEntries;
 
        string                  currency;
        uint16                             numTiers;
    }
    
    event nb(string cur);
    
    mapping (string => tierBase) private feeTables;
    
    function createTierBaseFor(string currency, address banker) {
  *      if (msg.sender != founder) throw;
        if (feeTables[currency].initialised) {
            log0("FeeTable exists");
            throw;
        }
        tierBase memory newBase;
        newBase.banker = banker;
        newBase.currency = currency;
        newBase.initialised = true;
        newBase.numTiers = 0;
        feeTables[currency] = newBase;
>        nb(newBase.currency);
        //setTierPercentages(0,currency,defBuy,defSell,defWeBuy,defWeSell,defStoreFee,"base rates");
    }
```

Step through to ">"

![image](https://cloud.githubusercontent.com/assets/1858302/22841999/a7439142-f00e-11e6-9e21-4d1e9ecff67f.png)

so you can see that the debugger shows the `newbase.currency` incorrectly, sometimes it is blank, on this run it was just weird. 

However, the event call shows that the actual variable was set OK.

![image](https://cloud.githubusercontent.com/assets/1858302/22842105/0046e51e-f00f-11e6-997f-c065d797a206.png)

![image](https://cloud.githubusercontent.com/assets/1858302/22842209/65642e84-f00f-11e6-821b-dec7549c653c.png)

**Comment by asinyagin** [comment]
@DaveAppleton thanks! I've reproduced it.

**Comment by asinyagin** [comment]
@DaveAppleton fixed and deployed. Check it please.
