### ISSUE TITLE
breakpoint in sub function kills sandbox

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#15]
In the code for issue 14, if we set a BP in the second function sandbox dies.

Note : it works if no breakpoint or BP in first fn.

![image](https://cloud.githubusercontent.com/assets/1858302/22843069/c761cf1c-f012-11e6-8b6a-9d0cefe1d3ce.png)

**Comment by romanman** [comment]
duplicate for #14
