### ISSUE TITLE
Call dialog output not always accurate

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#16]
In the call dialog for a function, parameters of type uint256 must be supplied as a decimal but results of uint256 are returned in hex.

```
  function multiplyB30(uint256 a, uint256 b) returns (uint256 result) {
        result = a * b / 1000000000000000000000000000000;
    }
```

![image](https://cloud.githubusercontent.com/assets/1858302/22880005/6eee1dc6-f21b-11e6-89a8-272bcd1da5c6.png)

however, (before the division) the answer is actually

```
6ea1a24c3b0e97cc5d84e22a7f61139c258b98f670000000000
```
(less than 256 bits)
or
```
11111111111111111111110000000000000000000000000000000000000000
```
so there is no way that there can be an overflow after the division and it should never be rounded up.

*NB : would be nice if it could actually show it as a number without the e+31 if possible*

**Comment by romanman** [comment]
@DaveAppleton it is standard way to show very big number, 
not really a bug.
