### ISSUE TITLE
dialog box opened - will not go away....

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#17]
I created a couple of contracts.

bank.sol and gift.sol

Gift.sol is supposed to be created dynamically (by bank) and has a constructor.
```
    function Gift(address recipient_, uint256 amount_, uint256 numDays) {
```

unfortunately, in my ethereum.json I had both "bank" and "Gift" to be deployed.

Since Gift was to be deployed, a dialog box was created asking for the three parameters.

This dialog cannot be dismissed even by stopping the sandbox.

![image](https://cloud.githubusercontent.com/assets/1858302/22905502/6b862844-f27b-11e6-8ef5-ae7bbc6f124d.png)

**Comment by asinyagin** [comment]
@DaveAppleton do you want to close the dialog? If you don't want to deploy Gift you can close the dialog or remove it from the ethereum.json.

**Comment by romanman** [comment]
@DaveAppleton can you be more precise, we can close it here

**Comment by DaveAppleton** [comment]
OK 
Have reset env to show this. open the bank.sol tab.
Debug active contract.
Wait - the dialog pops up.
No way to close it.
Stop the sandbox.
Still there.

**Comment by asinyagin** [comment]
Just tried it. You can close the dialog by clicking X at the top right or by pressing Esc.

**Comment by DaveAppleton** [comment]
Damn!!!!! So you can.

Is it just my settings that make it impossible to see the X unless you mouse over it?

![image](https://cloud.githubusercontent.com/assets/1858302/23032082/4bcc9d1e-f4ae-11e6-904f-3efe796f4895.png)

**Comment by asinyagin** [comment]
@DaveAppleton that's a bad UI theme.
