### ISSUE TITLE
Internal Error in Sandbox UI

### ISSUE THREAD

**Issue by ice09** [ether-camp/ethereum-sandbox#20]
With an ERC20 Token sample, I get "Internal Error" when I call a constant function like "totalSupply".

Steps to reproduce:
1. Use standard token
2. Deploy as "Run active contract", fill constructor values
3. Call function "totalSupply"

**Comment by asinyagin** [comment]
I think you're using an old version. My bad. I've updated `ice09.by.ether.camp` instead of `ethereum-meetup-mainz`.

**Comment by ice09** [comment]
Ah ok, then please update ethereum-meetup-mainz as well, you can do this whenever you have time.

**Comment by asinyagin** [comment]
Done. Check it please.

**Comment by ice09** [comment]
Looks much better, thanks!
