### ISSUE TITLE
transaction list overflowing and hiding later tx

### ISSUE THREAD

**Issue by SCBuergel** [ether-camp/ethereum-sandbox#21]
When reaching about 15 transactions the transactions view is overflowing and hiding later transactions as one cannot scroll:
![image](https://cloud.githubusercontent.com/assets/11379673/22975929/cfd9cdce-f388-11e6-9244-d8ae99df586e.png)

I would suggest to simply add a scrollbar similar to the contract sandbox interface.

**Comment by romanman** [comment]
thank, I did remember that I have seen it some whrere

**Comment by asinyagin** [comment]
@SCBuergel fixed and deployed. Check it please.

**Comment by SCBuergel** [comment]
@asinyagin, not really, now you simply increase the size of the box but the box easily grows beyond the size of my browser window. We need a scroll bar.

**Comment by SCBuergel** [comment]
This was a cache issue and is now working perfectly, thanks!
