### ISSUE TITLE
UI: exception details overflowing tx box

### ISSUE THREAD

**Issue by SCBuergel** [ether-camp/ethereum-sandbox#22]
When clicking on the details of a tx that has an exception the text is overflowing the box:
![image](https://cloud.githubusercontent.com/assets/11379673/22976231/362c7a30-f38a-11e6-9480-b3f0eb90b08c.png)

**Comment by asinyagin** [comment]
Thanks! That's a new exception message in solc. We probably should use it somehow.

**Comment by asinyagin** [comment]
@SCBuergel fixed and deployed. Check it please.

**Comment by SCBuergel** [comment]
@asinyagin, not working yet, still getting the overflowing box on sbuergel.by.ether.camp:
![image](https://cloud.githubusercontent.com/assets/11379673/23359441/83be49d0-fce6-11e6-8773-1acd64e0cd9d.png)

**Comment by asinyagin** [comment]
it was a cache issue.
