### ISSUE TITLE
`New scenario` on tx view just gives error message

### ISSUE THREAD

**Issue by SCBuergel** [ether-camp/ethereum-sandbox#25]
I get the following error message when clicking `New scenario` in the tx view:
![image](https://cloud.githubusercontent.com/assets/11379673/22977122/ba6239b8-f38d-11e6-9bfc-941943678255.png)

**Comment by asinyagin** [comment]
How can I reproduce it?

**Comment by SCBuergel** [comment]
You can start the sandbox on https://sbuergel.by.ether.camp from `workspace/blockchain/contracts/Drel.sol` and then in the terminal navigate to `workspace/blockchain/` and run my test via `node test.js`. I debugged a bit and it seems creating a new scenario stops working once I create a new contract via `web3.eth.contract(JSON.parse(propertyContractAbi)).new`.

**Comment by asinyagin** [comment]
@SCBuergel fixed and deployed. Check it please.

**Comment by SCBuergel** [comment]
@asinyagin checked, working - thanks!
