### ISSUE TITLE
[annoyance] [UI] Combobox resets to first account after transaction is sent.

### ISSUE THREAD

**Issue by 3esmit** [ether-camp/ethereum-sandbox#33]
How to reproduce:
When have more than one account in ethereum.json, open contract call window, go to advanced, select other than the first account in the combobox and do a contract call transaction. The account will reset to the first on the list.

If user got many accounts and want to execute more than one in this account, this is going to be annoying to always select again the account.

**Comment by romanman** [comment]
@3esmit we actually tried both options: 1 that you leave the last account 2. that you go back to default
and got to the conclusion that better to get back to default each time.
