### ISSUE TITLE
[annoyance] [UI] Expanded advanced tab keeps in front of contract functions

### ISSUE THREAD

**Issue by 3esmit** [ether-camp/ethereum-sandbox#34]
I was searching for a function in that window, and gone up and down many times looking for it, found out that it was under advanced tab.

![image](https://cloud.githubusercontent.com/assets/224810/23028941/ff4112d0-f44f-11e6-8980-0f402c6d9bb6.png)
![image](https://cloud.githubusercontent.com/assets/224810/23028969/12254c86-f450-11e6-9695-ae99ecbb74dd.png)

**Comment by romanman** [comment]
@3esmit : that is fine, you have the option to close the advanced dialog, 
don't see any option to actually solve it better

**Comment by 3esmit** [comment]
Just to register, it's really annoying this Advanced tab. It resets the value, the account, and I need to keep opening and closing it to access the function call button.
