### ISSUE TITLE
[enhancement] [UI] Keep account combobox always visible

### ISSUE THREAD

**Issue by 3esmit** [ether-camp/ethereum-sandbox#35]
Its common to change the account, we usually want to test function between accounts, but advanced things, such as value and gas settings is seldom use.

Suggested change:

![image](https://cloud.githubusercontent.com/assets/224810/23029244/fa5fcfb2-f450-11e6-879e-1164a48f2c4b.png)

**Comment by romanman** [comment]
@3esmit you are right, the account is really much more common in usage
but don't see any big deal in showing the 2 other fields.
