### ISSUE TITLE
Unable to run example "ether-camp/oraclize-example" Error: [object ProgressEvent] / Could not start sandbox: Sandbox is not available

### ISSUE THREAD

**Issue by 3esmit** [ether-camp/ethereum-sandbox#36]
How to reproduce it:

1. right click "workspace" -> "open terminal here"
2. enter `git clone https://github.com/ether-camp/oraclize-example.git`
3. open workspace/oraclize-example/contract.sol
4. press "run active contract": leads to `[object ProgressEvent]`
5. press "run active with debug": leads to `Sandbox is not available`

This seems to happen when this is added to ethereum.json:
```
  "plugins": {
    "oraclize": {
      "networkID": 161,
      "loadRealData": true
    }
  },
```

Tried reloading the ide, but still unable to make it run.

**Comment by romanman** [comment]
@asinyagin : good point, we didn't check oraclize for a long time
curious also if we have problems there

**Comment by romanman** [comment]
@bertani : I think we will need your help on the new version, 
are you around?

**Comment by romanman** [comment]
@3esmit :  fixed and deployed. Check it please.

**Comment by 3esmit** [comment]
Working fine.
