### ISSUE TITLE
Transaction list misses revelevant information

### ISSUE THREAD

**Issue by 3esmit** [ether-camp/ethereum-sandbox#37]
In order to have an analysis of contract calls efficiency, I would like to see gas usage information along with transaction list.

A complete transaction detail is nice to have, but mostly important ´Gas Used By Transaction´ should be along with that list. 

Other relevant information would be block information, there are some contracts that uses this information.

**Comment by romanman** [comment]
@3esmit click on the tx for the details.

**Comment by 3esmit** [comment]
@romanman I see it, didn't noticed that obvious thing. BTW, block information still missing, and data is enconded in hex. I know how to convert it, but I'm not that genious to read data in hex.

**Comment by romanman** [comment]
block info - don't you think on that sandbox chain it is kind of obsolete?

**Comment by 3esmit** [comment]
I don't know the full use cases for this information, but I might explore the idea of using block info for generating pseudo-randomness. 
If someone uses this information, maybe this person may want to analyse this information.

**Comment by romanman** [comment]
you still can develop the dapp using the prev hash as randomness source... wouldn't trust the enthropy of it... anyway omce deployed it should be good on the real chain
