### ISSUE TITLE
Transaction list overflow screen when many transactions are sent

### ISSUE THREAD

**Issue by 3esmit** [ether-camp/ethereum-sandbox#38]
My screen size can handle only 22 transactions, if more than this, I'm unable to access the buttons or other transactions down the list. 

![image](https://cloud.githubusercontent.com/assets/224810/23064433/392a679c-f4f7-11e6-9cbd-8d2727ff5d7e.png)

**Comment by romanman** [comment]
@asinyagin : is it a duplicate?

**Comment by 3esmit** [comment]
Hmm, I guess it is a duplicate of #21
