### ISSUE TITLE
Save dialog incomplete

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#4]
I had just updated a file and clicked the run button,
it asked me if I wanted to save.

![image](https://cloud.githubusercontent.com/assets/1858302/22665677/9211ed12-ecf0-11e6-9c24-191a5ee88a85.png)

**Comment by DaveAppleton** [comment]
The theme used in Issue #17 which hid the close box seems to handle this dialog better.

**Comment by asinyagin** [comment]
@DaveAppleton fixed and deployed. Check it please.
