### ISSUE TITLE
Addresses in a struct are listed in the outline....

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#7]
This may be intentional but I think unlikely :

uninstantiated address members of a struct are listed in the outline - which is a bit odd if the struct is repeated in a map 

![image](https://cloud.githubusercontent.com/assets/1858302/22709973/a26bf1fa-edb6-11e6-95be-ab22ba73e828.png)

![image](https://cloud.githubusercontent.com/assets/1858302/22710034/cdc81c98-edb6-11e6-85da-780c601759d9.png)

**Comment by romanman** [comment]
@DaveAppleton we are closing it as already report 
subject (duplicate) : we will work on the outline later.
