### ISSUE TITLE
sandbox stops after debugging first function

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#8]
Sandbox seems to stop after debugging a single function
==============
Steps to reproduce
----------------------------------------------------------

In the contract that I have loaded, start debugging

set breakpoint at line 383 (first line of approveuser)

you have to call setCustomerService first, currency = MYR, address = 0xdedb49385ad5b94a16f236a6890cf9e0b1e30392 (address of founder / sender)

then call approveUser from the same address approving same user (0xdedb49385ad5b94a16f236a6890cf9e0b1e30392) and MYR

when you reach the end of the last line the sandbox stops.

Set breakpoint
![image](https://cloud.githubusercontent.com/assets/1858302/22775944/ca0ab9ca-eee8-11e6-88f8-2fc4998cd609.png)

Start debugging
![image](https://cloud.githubusercontent.com/assets/1858302/22775958/db47fbe4-eee8-11e6-8e95-4646d1d33765.png)

Bring up contract's UI
![image](https://cloud.githubusercontent.com/assets/1858302/22775987/f47f808c-eee8-11e6-8baa-6b9340aa0659.png)

setCustomerServiceFor
![image](https://cloud.githubusercontent.com/assets/1858302/22776094/53009916-eee9-11e6-9687-3c78c7084a81.png)

approveUser
![image](https://cloud.githubusercontent.com/assets/1858302/22776143/839d8e94-eee9-11e6-9a4e-2aeff35b493d.png)
(you see the tx being mined but obviously we are pausing it)

this is nice 
![image](https://cloud.githubusercontent.com/assets/1858302/22776195/b31431c8-eee9-11e6-9ad1-9becba15aa84.png)

but as you step out
![image](https://cloud.githubusercontent.com/assets/1858302/22776218/cdaaf418-eee9-11e6-8840-d42ade2d9183.png)

**Comment by asinyagin** [comment]
@DaveAppleton thanks! I'll fix it asap.

**Comment by asinyagin** [comment]
@DaveAppleton I've updated your ide with the fix.
