### ISSUE TITLE
After several sub calls, on leaving a breakpointed  function the debug window does not return to usual state (so can't get dialog to do more transactions)

### ISSUE THREAD

**Issue by DaveAppleton** [ether-camp/ethereum-sandbox#9]
Following the previous issue do the following

set a breakpoint at
![image](https://cloud.githubusercontent.com/assets/1858302/22781579/1a8b01b0-eefe-11e6-89b0-63ab73aca037.png)

And note debug state is 
![image](https://cloud.githubusercontent.com/assets/1858302/22781596/2ff41d7a-eefe-11e6-967e-c11bfb9bc322.png)

Now - setBanker to MYR / 0xdedb49385ad5b94a16f236a6890cf9e0b1e30392

ApproveUser : MYR / 0xdedb49385ad5b94a16f236a6890cf9e0b1e30392

then 
depositCash
![image](https://cloud.githubusercontent.com/assets/1858302/22782293/4fbf7912-ef01-11e6-922e-08a3ea8caa82.png)

(Love the showing of variables)

Then keep stepping in  
![image](https://cloud.githubusercontent.com/assets/1858302/22782338/8f79ef06-ef01-11e6-99a4-71fedc19aa6f.png)

481->482->481->483->(goes through function to return to 483)->481->86

At this time it is clear that the values of b are wrong ! 256000 represents exp = 3, val = 1 but I will visit that in another report

![image](https://cloud.githubusercontent.com/assets/1858302/22782427/1413c138-ef02-11e6-84f3-a3290d331843.png)

Trace it 86, 89, 92
fails to go to 90 despite debugger saying that b.exponent > a.exponent

step over 92
![image](https://cloud.githubusercontent.com/assets/1858302/22782630/f50b96e8-ef02-11e6-8bf6-c5e58ae97178.png)
res.value has not been assigned

If you now resume, it gets out to the breakpoint again. Resume once more and you get
![image](https://cloud.githubusercontent.com/assets/1858302/22782706/59e6bc50-ef03-11e6-92be-0b33d571681a.png)

Which means that you can no longer get the contract interface back up. (right hand panel should be showing the contract space again as in second image.

**Comment by DaveAppleton** [comment]
Scratch the last bit - I am stupid - missed the sandbox tab - sorry.

**Comment by DaveAppleton** [comment]
Seems that despite the debugger issues above, the real calculations happened correctly

![image](https://cloud.githubusercontent.com/assets/1858302/22783242/e3a0bc6e-ef05-11e6-9ffb-a12f481d5cc5.png)

**Comment by 3esmit** [comment]
I'm having the same issue. Seems like the transactions stop being mined. Quering a constant state function works, but transactions that need to be mined are hanged.

**Comment by 3esmit** [comment]
This happens when using scenarios.

**Comment by romanman** [comment]
yep that is important stability issue

**Comment by asinyagin** [comment]
Fixed
